core-wg/coap-tcp-tls

draft-ietf-core-coap-tcp-tls.md

(includes original proposal for resolution of #387; this may need
further updates.)

Editorial fixes as proposed by Hannes

---

draft-ietf-core-coap-tcp-tls.md

This is an extremely rough merge of core-coap-tcp-tls and core-coap-websockets. The main intent was to get all the material into one draft with a potential outline and next perform an overall editorial pass.

"Roughed in" merge of draft-savolainen-core-coap-websockets

---

draft-ietf-core-coap-tcp-tls.md

Moves Acknowledgements to back
Adds Contributions to back
Closes #10

Updating Acknowledgements and Contributions section

---

draft-ietf-core-coap-tcp-tls.md

This is the first version of the CoAP reliable transports - _one draft to rule them all_

Merge of sig-02 with additional edits

---

draft-ietf-core-coap-tcp-tls.md

Abstract updates

---

draft-ietf-core-coap-tcp-tls.md

Introduction and Terminology Updates

---

draft-ietf-core-coap-tcp-tls.md

CoAP over TCP Updates

---

draft-ietf-core-coap-tcp-tls.md

Adapted changes from Hannes - primarily moving BERT to follow the Signal section.

BERT updates

---

draft-ietf-core-coap-tcp-tls.md

Closes #25 
Closes #27  
Closes #28

Updates to Signaling section

---

draft-ietf-core-coap-tcp-tls.md

Updates to clarify length and extended length

---

draft-ietf-core-coap-tcp-tls.md

Updated lengths for uint options

---

draft-ietf-core-coap-tcp-tls.md

consistent use of coap over

---

draft-ietf-core-coap-tcp-tls.md

Updated ietf-dice-profile reference to RFC7925
Closes #8 
Closes #11

Security Considerations: Initial changes

---

draft-ietf-core-coap-tcp-tls.md

ALPN and port 5684

---

draft-ietf-core-coap-tcp-tls.md

CoAP and WebSocket Pings

---

draft-ietf-core-coap-tcp-tls.md

Mandatory exchange of CSM

---

draft-ietf-core-coap-tcp-tls.md

Editorial updates

---

draft-ietf-core-coap-tcp-tls.md

updating references

---

draft-ietf-core-coap-tcp-tls.md

Closes #58
Also clarifies that "same kind" in Alternate-Address refers to scheme.

Updates to Section 2.3

---

draft-ietf-core-coap-tcp-tls.md

Performing an editorial pass during WGLC ... more commits to come ...

WGLC editorial changes

---

draft-ietf-core-coap-tcp-tls.md

Also updated one more case of "messaging layer" rather than "message layer of"
Closes #92

Remove the UDP to TCP gateway section

---

draft-ietf-core-coap-tcp-tls.md

Refine IANA - Signaling Option Numbers

---

draft-ietf-core-coap-tcp-tls.md

Updates for reliable transport

---

draft-ietf-core-coap-tcp-tls.md

Added RFC7641 formal update to abstract and introduction

---

draft-ietf-core-coap-tcp-tls.md

And changed Len to Len=0 for websocket message format in Figure 14.
Closes #87

Added explanation for payload marker

---

draft-ietf-core-coap-tcp-tls.md

Closes #12 
Closes #75 
Closes #78 
Closes #91

Harmonious URI schemes and registrations

---

draft-ietf-core-coap-tcp-tls.md

Address feedback from  Hannes - https://www.ietf.org/mail-archive/web/core/current/msg08234.html
Minor updates to #11

Securing CoAP: Feedback from Hannes and other editorial changes

---

draft-ietf-core-coap-tcp-tls.md

Closes #71 
Closes #73 
Closes #80 
Closes #88

WGLC updates for WebSockets

---

draft-ietf-core-coap-tcp-tls.md

Closes #66 
Closes #77
Closes #81

Updates to Signaling Option Numbers

---

draft-ietf-core-coap-tcp-tls.md

Also addresses #104 (and integrates #103).

Editorial changes discussed in 2017-02-02 authors' call

---

draft-ietf-core-coap-tcp-tls.md

Closes #102 
@bsilverajan - can you review (don't see you in the Reviewers list)?

Securing WebSockets

---

draft-ietf-core-coap-tcp-tls.md

BERT and Max-Message-Size dependency

---

draft-ietf-core-coap-tcp-tls.md

Addition of defaults for uri-host and uri-port options

---

draft-ietf-core-coap-tcp-tls.md

Second WGLC editorial changes

---

draft-ietf-core-coap-tcp-tls.md

Semantics for multiple Alternative-Address Options

---

draft-ietf-core-coap-tcp-tls.md

Guidance for message format errors

---

.gitignore
Makefile2
draft-ietf-core-coap-tcp-tls.md
rfc3986.abnf

Oops, I did this on master -- please merge with your changes in 125...

Fix ABNF; add ABNF check to Makefile2

---

draft-ietf-core-coap-tcp-tls.md

Add well-known support to RFC 6455 for ws:, wss:

---

draft-ietf-core-coap-tcp-tls.md

Closes #132 
Updates for acronyms
Minor style change to Abstract

Editorial changes from gen-art review

---

draft-ietf-core-coap-tcp-tls.md

Artart review: NoSec is optional

---

draft-ietf-core-coap-tcp-tls.md

Closes #129 
Add to Updates
Updated Abstract
Added IANA section to update related references for Block1 and Block2

BERT updates RFC7959

---

draft-ietf-core-coap-tcp-tls.md

updated acknowledgements

---

draft-ietf-core-coap-tcp-tls.md

Added proposed clarification

---

draft-ietf-core-coap-tcp-tls.md

Pong editorial

---

draft-ietf-core-coap-tcp-tls.md

no state transfer for alternative-address connection

---

draft-ietf-core-coap-tcp-tls.md

Reverts references to uri fragment identifiers

---

draft-ietf-core-coap-tcp-tls.md

Signaling messages are only for reliable tranports

---

draft-ietf-core-coap-tcp-tls.md

Editorial feedback from Ben Campbell
